DROP TABLE IF EXISTS sentences;
CREATE TABLE sentences(
    ID VARCHAR2(255) PRIMARY KEY,
    TEXT VARCHAR2(255)
);

INSERT INTO sentences VALUES
('IMAGE_REACT_HFACE', 'U+1F975'),
('IMAGE_REACT_CFACE', 'U+1F976'),
('IMAGE_REACT_SKULL', 'U+2620'),
('IMAGE_REACT_JOY', 'U+1F602'),
('IMAGE_REACT_SCREAM', 'U+1F631'),
('IMAGE_REACT_GRIM', 'U+1F62C'),
('IMAGE_REACT_100', 'U+1F4AF'),

('DEFAULT_RESTRICT', 'AI VOIE SA SCRII DOAR IN @@'),
('DEFAULT_MUSIC_RESTRICT', 'AICI SE PUNE DOAR MUZICA'),
('DEFAULT_NOCOMMAND', '???'),

('MUSIC_WRONG_CHANNEL', 'DOAR PE @@ SE PUNE MUZICA'),
('MUSIC_LOAD_PLAYLIST', 'NU PUN PLAYLIST-URI'),
('MUSIC_LOAD_NO_MATCHES', 'NU AM GASIT NIMIC'),
('MUSIC_LOAD_FAILED', 'NU MERGE'),
('MUSIC_SKIP_NOSONG', 'NU AM LA CE SA DAU SKIP'),

('MUSIC_SKIP_FAILED_1', 'Nu dau skip, imi place');
